# Generated by Django 3.0.6 on 2020-09-17 05:01

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.upload_location),
        ),
    ]
