# Generated by Django 3.0.6 on 2020-09-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='pic',
        ),
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(default='media_cdn/blog/1/hero.jpg', upload_to=''),
        ),
    ]
