# Generated by Django 3.0.6 on 2020-10-12 19:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200916_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
