# Generated by Django 3.0.6 on 2020-10-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201012_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, default='images_4.jpeg', upload_to=''),
        ),
    ]
