# Generated by Django 3.0.6 on 2020-10-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('Sweets', 'Sweets'), ('Healthy', 'Healthy'), ('Pastry', 'Pastry')], max_length=7),
        ),
    ]
