# Generated by Django 3.0.6 on 2020-10-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201011_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, default='images_4.jpeg', upload_to=''),
        ),
    ]
